baseUrl=https://practice.expandtesting.com/notes/app/login

dashboardUrl=https://practice.expandtesting.com/notes/app

apiBaseUrl=https://practice.expandtesting.com/notes/api

email=apple1@gmail.com

password=1apple

browser=chrome

runMode=local

gridUrl=http://localhost:4444