pipeline {

    agent any

    tools {

        maven 'Maven'
        jdk 'JDK21'

    }

    stages {

        stage('Build and Test') {

            steps {

                dir('Notes_15') {

                    bat 'mvn clean test'

                }

            }

        }

        stage('Generate Allure Report') {

            steps {

                dir('Notes_15') {

                    allure includeProperties: false,
                           jdk: '',
                           results: [[path: 'allure-results']]

                }

            }

        }

        stage('Publish HTML Report') {

            steps {

                publishHTML([
                        allowMissing         : false,
                        alwaysLinkToLastBuild: true,
                        keepAll              : true,
                        reportDir            : 'Notes_15/test-output',
                        reportFiles          : 'emailable-report.html',
                        reportName           : 'TestNG HTML Report'
                ])

            }

        }

    }

}
