pipeline {

    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    stages {

        stage('Build and Test') {
            steps {

                bat 'mvn clean test'
            }
        }

        stage('Generate Allure Report') {
            steps {

                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'allure-results']]
                )
            }
        }

        stage('Publish HTML Report') {
            steps {

                publishHTML(target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/surefire-reports',
                    reportFiles: 'emailable-report.html',
                    reportName: 'TestNG HTML Report'
                ])
            }
        }
    }

    post {

        always {

            archiveArtifacts artifacts: 'screenshots/*.png', allowEmptyArchive: true

            junit 'target/surefire-reports/*.xml'
        }
    }
}