pipeline {

    agent any

    tools {

        maven 'Maven'
        jdk 'JDK21'

    }

    stages {

        stage('Build and Test') {

            steps {

                dir('Notes_15') {

                    bat 'mvn clean test'

                }

            }

        }

        stage('Generate Allure Report') {

            steps {

                dir('Notes_15') {

                    allure includeProperties: false,
                           jdk: '',
                           results: [[path: 'allure-results']]

                }

            }

        }

        stage('Run JMeter Tests') {

            steps {

                dir('Notes_15') {

                    bat '''
                    jmeter -n ^
                    -t performance/jmeter/testplans/testplan.jmx ^
                    -l performance/jmeter/results/results.jtl ^
                    -j performance/jmeter/results/jmeter.log
                    '''

                    bat '''
                    jmeter -g performance/jmeter/results/results.jtl ^
                    -o performance/jmeter/results/html-report
                    '''

                }

            }

        }

        stage('Publish JMeter Report') {

            steps {

                publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'Notes_15/performance/jmeter/results/html-report',
                    reportFiles: 'index.html',
                    reportName: 'JMeter HTML Report'
                ])

            }

        }

    }

}
